version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  clean: true  # Always start fresh by ignoring cached files

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
