version: 2  # Required version

# Specify the build configuration for RTD
build:
  # Always force a full clean build by ignoring cached files
  clean: true

python:
  version: 3.10 # Specify the Python version you want to use

  # Install the project dependencies using requirements.txt
  install:
    - requirements: docs/requirements.txt  # Path to your requirements.txt file

  # Force a full reinstallation of all dependencies
  system_packages: false  # Avoid using cached system packages
  
  # Additional pip packages to install, if necessary
  extra_requirements:
    - docs  # For example, if you have an extras_require for docs in setup.py

# Add environment variables if needed (optional)
# env:
#   MY_ENV_VAR: value

# Always trigger a full rebuild without caching
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file
  builder: html  # Specify the builder, e.g., html, latexpdf, etc.

# Optionally specify conda (if you use conda for environment management)
# conda:
#   environment: environment.yml  # If you have a conda environment file

