version: 2

python:
  version: 3.10

  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

# Optional: Add environment variables to pass verbosity or other build options
env:
  - SPHINXOPTS=-vv  # Very verbose output for debugging (remove if not needed)
