version: 2

python:
  version: 3.10

  install:
    - requirements: docs/requirements.txt

build:
  # This tells RTD to ignore previous builds and start fresh each time
  clean: true
  os: ubuntu-22.04
  tools:


sphinx:
  configuration: docs/conf.py
  builder: html
