version: 2  # Required version

# Configure Python environment
python:
  version: 3.10  # Specify the Python version you need

  install:
    - requirements: docs/requirements.txt  # Ensure this path matches your actual file location

# Force a clean build by ignoring cached files
build:
  image: "latest"  # Use the latest Read the Docs build image

# Specify Sphinx configuration
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file
  builder: html  # Generate HTML documentation
