version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
  system_packages: false  # Avoid using cached system packages for a fresh build

sphinx:
  configuration: docs/conf.py
