version: 2

python:
  version: 3.8

  install:
    - requirements: docs/requirements.txt

build:
  # This tells RTD to ignore previous builds and start fresh each time
  clean: true

sphinx:
  configuration: docs/conf.py
  builder: html
