version: 2  # Configuration version

python:
  version: 3.10

  install:
    - requirements: docs/requirements.txt  # Path to requirements.txt

sphinx:
  configuration: docs/conf.py  # Path to Sphinx configuration file (conf.py)

build:
  tools:
    python: "3.10"

# Pass Sphinx options (like verbosity) through environment variables
env:
  - SPHINXOPTS=-vv
