version: 2  # The version of the RTD configuration format

python:
  version: 3.10 # Your desired Python version

  install:
    - requirements: docs/requirements.txt  # Path to your requirements file

sphinx:
  configuration: docs/conf.py  # Path to your conf.py file for Sphinx

build:
  image: latest  # Use the latest RTD build image

env:
  - SPHINXOPTS=-v  # Enable verbose mode for Sphinx (-vv for even more detail)
